from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Protocol, runtime_checkable

from dojo.model import (
    AuditEvent,
    Client,
    ConsentAcceptance,
    ConsentPolicy,
    Job,
    Package,
    PairingCode,
    ProcessedMedia,
    Upload,
)


@runtime_checkable
class Clock(Protocol):
    def now(self) -> datetime: ...


@runtime_checkable
class PackageStore(Protocol):
    def create(self, package: Package) -> Package: ...
    def get_active(self) -> Package | None: ...
    def update(self, package: Package) -> Package: ...


@runtime_checkable
class AuditStore(Protocol):
    def append(self, event: AuditEvent) -> None: ...
    def list_recent(
        self, limit: int = 50, before_id: int | None = None
    ) -> list[AuditEvent]: ...


@runtime_checkable
class MetaPublisher(Protocol):
    def publish_reel(self, signed_url: str, caption: str) -> None: ...


@runtime_checkable
class Notifier(Protocol):
    def notify(self, title: str, body: str) -> None: ...


@runtime_checkable
class SignedUrlStore(Protocol):
    def create(self, artifact_path: Path) -> str: ...
    def revoke(self, url: str) -> None: ...


@runtime_checkable
class Hasher(Protocol):
    def hash(self, secret: str) -> str: ...


@runtime_checkable
class SecretGenerator(Protocol):
    def generate_code(self) -> str: ...
    def generate_token(self) -> str: ...


@runtime_checkable
class PairingStore(Protocol):
    def create_code(self, code: PairingCode) -> PairingCode: ...
    def find_code_by_hash(self, code_hash: str) -> PairingCode | None: ...
    def mark_code_consumed(self, code_id: int, at: datetime) -> bool: ...
    def find_client_by_id(self, client_id: int) -> Client | None: ...
    def create_client(self, client: Client, credential_hash: str) -> Client: ...
    def find_client_by_credential_hash(self, credential_hash: str) -> Client | None: ...
    def list_clients(self) -> list[Client]: ...
    def mark_client_revoked(self, client_id: int, at: datetime) -> None: ...
    def touch_client(self, client_id: int, at: datetime) -> None: ...


@runtime_checkable
class SetupStore(Protocol):
    def create_policy(
        self, *, version: int, text: str, created_by: str, created_at: datetime
    ) -> ConsentPolicy: ...

    def get_current_policy(self) -> ConsentPolicy | None: ...
    def get_policy(self, version: int) -> ConsentPolicy | None: ...
    def find_acceptance(self, policy_version: int) -> ConsentAcceptance | None: ...
    def record_acceptance(self, acceptance: ConsentAcceptance) -> bool: ...


@runtime_checkable
class UploadStore(Protocol):
    def create(self, upload: Upload) -> Upload: ...
    def get(self, upload_id: str) -> Upload | None: ...
    def get_by_pk(self, upload_pk: int) -> Upload | None: ...
    def update(self, upload: Upload) -> Upload: ...
    def list_active(self) -> list[Upload]: ...
    def list_stale(self, cutoff: datetime) -> list[Upload]: ...


@runtime_checkable
class JobStore(Protocol):
    def create(self, job: Job) -> Job: ...
    def get(self, job_id: str) -> Job | None: ...
    def get_by_upload(self, upload_pk: int) -> Job | None: ...
    def update(self, job: Job) -> Job: ...
    def claim_next(self, claimed_at: datetime) -> Job | None: ...


@runtime_checkable
class SettingsStore(Protocol):
    def get(self, key: str) -> object | None: ...
    def set(self, key: str, value: object, *, updated_at: datetime) -> None: ...


@runtime_checkable
class MediaProcessor(Protocol):
    def process(
        self, upload: Upload, original_path: Path, work_dir: Path
    ) -> ProcessedMedia: ...
