from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Protocol, runtime_checkable

from dojo.model import AuditEvent, Client, ConsentAcceptance, ConsentPolicy, Package, PairingCode


@runtime_checkable
class Clock(Protocol):
    def now(self) -> datetime: ...


@runtime_checkable
class PackageStore(Protocol):
    def create(self, package: Package) -> Package: ...
    def get_active(self) -> Package | None: ...
    def update(self, package: Package) -> Package: ...


@runtime_checkable
class AuditStore(Protocol):
    def append(self, event: AuditEvent) -> None: ...
    def list_recent(
        self, limit: int = 50, before_id: int | None = None
    ) -> list[AuditEvent]: ...


@runtime_checkable
class MetaPublisher(Protocol):
    def publish_reel(self, signed_url: str, caption: str) -> None: ...


@runtime_checkable
class Notifier(Protocol):
    def notify(self, title: str, body: str) -> None: ...


@runtime_checkable
class SignedUrlStore(Protocol):
    def create(self, artifact_path: Path) -> str: ...
    def revoke(self, url: str) -> None: ...


@runtime_checkable
class Hasher(Protocol):
    def hash(self, secret: str) -> str: ...


@runtime_checkable
class SecretGenerator(Protocol):
    def generate_code(self) -> str: ...
    def generate_token(self) -> str: ...


@runtime_checkable
class PairingStore(Protocol):
    def create_code(self, code: PairingCode) -> PairingCode: ...
    def find_code_by_hash(self, code_hash: str) -> PairingCode | None: ...
    def mark_code_consumed(self, code_id: int, at: datetime) -> bool: ...
    def find_client_by_id(self, client_id: int) -> Client | None: ...
    def create_client(self, client: Client, credential_hash: str) -> Client: ...
    def find_client_by_credential_hash(self, credential_hash: str) -> Client | None: ...
    def list_clients(self) -> list[Client]: ...
    def mark_client_revoked(self, client_id: int, at: datetime) -> None: ...
    def touch_client(self, client_id: int, at: datetime) -> None: ...


@runtime_checkable
class SetupStore(Protocol):
    def create_policy(
        self, *, version: int, text: str, created_by: str, created_at: datetime
    ) -> ConsentPolicy: ...

    def get_current_policy(self) -> ConsentPolicy | None: ...
    def get_policy(self, version: int) -> ConsentPolicy | None: ...
    def find_acceptance(self, policy_version: int) -> ConsentAcceptance | None: ...
    def record_acceptance(self, acceptance: ConsentAcceptance) -> bool: ...
